// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/StoreForm/StoreForm.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BentoAlert, BentoButton } from '@adyen/bento-vue3';
import SelectField from '../../fields/SelectField.vue';
import { useWizard } from '../../../composables/wizardContext';
import { PAYMENT_LINK_CREATION_CLASS_NAMES } from '../../../../../../domain/src';
import type { IPaymentLinkSettings, IPaymentLinkStore } from '@integration-components/types';
import type { TranslationKey } from '@integration-components/core';
import './StoreForm.scss';

const props = defineProps<{
    selectItems: { id: string; name: string }[];
    settingsData?: IPaymentLinkSettings;
    storesData?: IPaymentLinkStore[];
    termsAndConditionsProvisioned: boolean;
    canModifySettings: boolean;
}>();

const emit = defineEmits<{
    setupTermsAndConditions: [];
}>();

const wizard = useWizard();
const { i18n } = wizard;
const CLASS_NAMES = PAYMENT_LINK_CREATION_CLASS_NAMES;

const selectedStoreId = computed(() => wizard.getValue('store'));
const showTcAlert = computed(() => !!props.settingsData && !!props.storesData && !!selectedStoreId.value && !props.termsAndConditionsProvisioned);
const alertDescriptionKey = computed<TranslationKey>(() =>
    props.canModifySettings
        ? 'payByLink.creation.storeForm.alerts.tcSetupRequired'
        : 'payByLink.creation.storeForm.alerts.tcSetupRequiredWithoutPermissions'
);

function handleSetupTermsAndConditions() {
    emit('setupTermsAndConditions');
}
</script>

<template>
    <div :class="CLASS_NAMES.fieldsContainer">
        <SelectField name="store" :label="i18n.get('payByLink.creation.fields.store.label')" :items="props.selectItems" />
        <BentoAlert v-if="showTcAlert" :class="CLASS_NAMES.tcAlert" type="warning" role="alert">
            {{ i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredTitle') }}
            <template #description>
                {{ i18n.get(alertDescriptionKey) }}
                <BentoButton v-if="props.canModifySettings" variant="tertiary" @click="handleSetupTermsAndConditions">
                    {{ i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredAction') }}
                </BentoButton>
            </template>
        </BentoAlert>
    </div>
</template>

// packages/domains/payByLink/preact/src/PaymentLinkCreation/components/Form/StoreForm/StoreForm.tsx
import { useConfigContext, useCoreContext } from '@integration-components/core/preact';
import Alert from '@integration-components/ui-components-preact/Alert/Alert';
import { AlertTypeOption } from '@integration-components/ui-components-preact/Alert/types';
import StoreField from './Fields/StoreField';

import { StateUpdater, useMemo } from 'preact/hooks';
import { PaymentLinkCreationFormValues } from '../../../types';
import { useWizardFormContext } from '@integration-components/hooks-preact/form/wizard/WizardFormContext';
import { IPaymentLinkSettings, IPaymentLinkStore } from '@integration-components/types';
import { Dispatch } from 'preact/compat';
import type { StoreIds } from '@integration-components/payByLink/domain';
import './StoreForm.scss';

interface StoreFormProps {
    setShowTermsAndConditions: Dispatch<StateUpdater<boolean>>;
    storeIds?: StoreIds;
    settingsData?: IPaymentLinkSettings;
    storesData?: IPaymentLinkStore[];
    selectItems: { id: string; name: string }[];
    termsAndConditionsProvisioned: boolean;
}

export const StoreForm = ({ setShowTermsAndConditions, settingsData, storesData, selectItems, termsAndConditionsProvisioned }: StoreFormProps) => {
    const { i18n } = useCoreContext();
    const { savePayByLinkSettings } = useConfigContext().endpoints;
    const { getValues } = useWizardFormContext<PaymentLinkCreationFormValues>();
    const canModifySettings = !!savePayByLinkSettings;

    const selectedStoreId = getValues('store');

    const alertLabel = useMemo(() => {
        if (!termsAndConditionsProvisioned) {
            if (canModifySettings) {
                return 'payByLink.creation.storeForm.alerts.tcSetupRequired';
            }
            return 'payByLink.creation.storeForm.alerts.tcSetupRequiredWithoutPermissions';
        }
    }, [termsAndConditionsProvisioned, canModifySettings]);

    const alertActions = useMemo(() => {
        if (!canModifySettings) {
            return [];
        }
        return [
            {
                label: i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredAction'),
                onClick: () => {
                    setShowTermsAndConditions(true);
                },
            },
        ];
    }, [canModifySettings, setShowTermsAndConditions, i18n]);

    return (
        <div className="adyen-pe-payment-link-creation-form__fields-container">
            <StoreField items={selectItems} />
            {settingsData && storesData && selectedStoreId && !termsAndConditionsProvisioned && (
                <Alert
                    className="adyen-pe-payment-link-creation-form__tc-alert"
                    title={i18n.get('payByLink.creation.storeForm.alerts.tcSetupRequiredTitle')}
                    type={AlertTypeOption.WARNING}
                    description={alertLabel && i18n.get(alertLabel)}
                    actions={alertActions}
                />
            )}
        </div>
    );
};
