// packages/domains/payByLink/preact/src/PaymentLinkCreation/components/Form/PaymentDetailsForm/Fields/ValidityField.tsx
import { useCoreContext } from '@integration-components/core/preact';
import { useMemo, useCallback, useState, useEffect } from 'preact/hooks';
import { FunctionalComponent, JSX } from 'preact';
import { IPaymentLinkValidity, IPaymentLinkConfiguration } from '@integration-components/types';
import { TranslationKey } from '@integration-components/core';
import { PaymentLinkCreationFormValues } from '../../../../types';
import { useWizardFormContext } from '@integration-components/hooks-preact/form/wizard/WizardFormContext';
import { VisibleField } from '@integration-components/ui-components-preact/FormWrappers/VisibleField';
import FormField from '@integration-components/ui-components-preact/FormWrappers/FormField';
import { Controller } from '@integration-components/hooks-preact/form';
import Select from '@integration-components/ui-components-preact/FormFields/Select';
import { LINK_VALIDITY_DURATION_UNITS } from '../../../../../../../domain/src';
import InputBase from '@integration-components/ui-components-preact/FormFields/InputBase';
import { transformToMS } from '@integration-components/utils';
import { SelectChangeEvent } from '@integration-components/ui-components-preact/FormFields/Select/types';
import { FieldError } from '@integration-components/ui-components-preact/FormFields/FieldError/FieldError';

export type ValidityFieldProps = {
    configuration?: IPaymentLinkConfiguration;
};

const MAX_VALIDITY_DAYS = 70;
const FLEXIBLE_ID = 'flexible';

export const ValidityField: FunctionalComponent<ValidityFieldProps> = ({ configuration }) => {
    const [customDurationUnit, setCustomDurationUnit] = useState('');
    const [customDurationQuantity, setCustomDurationQuantity] = useState<number | undefined>(undefined);
    const [validityValue, setValidityValue] = useState('');
    const { i18n } = useCoreContext();
    const { control, fieldsConfig, setValue, getValues, trigger } = useWizardFormContext<PaymentLinkCreationFormValues>();

    const getValidityFromFormState = useCallback(
        () => [getValues('linkValidity.durationUnit'), getValues('linkValidity.quantity')] as const,
        [getValues]
    );

    const validitySelectItems = useMemo(() => {
        const options: IPaymentLinkValidity[] = configuration?.linkValidity?.options ?? [];
        return options.map(({ quantity, durationUnit, type }) => {
            if (type === FLEXIBLE_ID) {
                return { id: FLEXIBLE_ID, name: i18n.get('payByLink.creation.fields.validity.linkValidityUnit.custom') };
            }
            const key: TranslationKey = `payByLink.creation.fields.validity.linkValidityUnit.${durationUnit}`;
            return { id: `${quantity} ${durationUnit}`, name: i18n.get(key, { values: { quantity }, count: quantity }) };
        });
    }, [configuration, i18n]);

    const initializeDefaultValidity = useCallback(() => {
        if (!validitySelectItems.length) return;
        const [durationUnit, quantity] = getValidityFromFormState();
        if (!quantity || !durationUnit) {
            const [qty, unit] = `${validitySelectItems[0]?.id}`.split(' ');
            setValue('linkValidity.quantity', qty);
            setValue('linkValidity.durationUnit', unit);
        }
    }, [validitySelectItems, setValue, getValidityFromFormState]);

    const findCurrentOption = useCallback(() => {
        const [durationUnit, quantity] = getValidityFromFormState();
        if (!quantity || !durationUnit) return validitySelectItems[0];
        return validitySelectItems.find(item => item.id === `${quantity} ${durationUnit}`) || { id: FLEXIBLE_ID };
    }, [validitySelectItems, getValidityFromFormState]);

    useEffect(() => {
        const [durationUnit, quantity] = getValidityFromFormState();
        setCustomDurationUnit(durationUnit || '');
        setCustomDurationQuantity(quantity || '');
        setValidityValue(findCurrentOption()?.id || '');
        initializeDefaultValidity();
    }, [getValidityFromFormState, validitySelectItems, findCurrentOption, initializeDefaultValidity]);

    const isDurationUnitRequired = fieldsConfig['linkValidity.durationUnit']?.required;
    const isDurationQuantityRequired = fieldsConfig['linkValidity.quantity']?.required;
    const isReadOnly = fieldsConfig['linkValidity.durationUnit']?.readOnly || fieldsConfig['linkValidity.quantity']?.readOnly;

    const handleCustomDurationQuantityChange = useCallback(
        (e: JSX.TargetedEvent<HTMLInputElement>) => {
            const eventValue = (e.target as HTMLInputElement)?.value;
            const newQuantity = parseInt(eventValue, 10);
            setValue('linkValidity.quantity', newQuantity);
            setCustomDurationQuantity(newQuantity);
            trigger('linkValidity.durationUnit');
        },
        [setValue, trigger]
    );

    const handleCustomDurationUnitChange = useCallback(
        (selectedValue: string) => {
            setValue('linkValidity.durationUnit', selectedValue);
            setCustomDurationUnit(selectedValue);
            trigger('linkValidity.quantity');
        },
        [setValue, trigger]
    );

    const dropdownItems = useMemo(
        () =>
            LINK_VALIDITY_DURATION_UNITS.map(unit => ({
                id: unit,
                name: i18n.get(`payByLink.creation.fields.validity.linkValidityUnit.${unit}__plural`),
            })),
        [i18n]
    );

    const validate = useCallback(() => {
        if (validityValue !== FLEXIBLE_ID) return { valid: true };

        const [durationUnit, durationQuantity] = getValidityFromFormState();
        const qty = parseInt(durationQuantity, 10);

        if (!durationQuantity) {
            return { valid: false, message: i18n.get('payByLink.creation.fields.validity.customDuration.error.missingDurationValue') };
        }
        if (isNaN(qty) || qty <= 0) {
            return { valid: false, message: i18n.get('payByLink.creation.fields.validity.customDuration.error.invalidDurationValue') };
        }
        if (!durationUnit) {
            return { valid: false, message: i18n.get('payByLink.creation.fields.validity.customDuration.error.missingDurationUnit') };
        }
        // TODO: Change to use config
        if (transformToMS(durationUnit, qty) > transformToMS('day', MAX_VALIDITY_DAYS)) {
            return {
                valid: false,
                message: i18n.get('payByLink.creation.fields.validity.customDuration.error.durationTooLong', {
                    values: { maxDays: MAX_VALIDITY_DAYS },
                }),
            };
        }
        return { valid: true };
    }, [validityValue, i18n, getValidityFromFormState]);

    return (
        <VisibleField<PaymentLinkCreationFormValues> name="linkValidity.durationUnit">
            <Controller<PaymentLinkCreationFormValues>
                name="linkValidity.durationUnit"
                control={control}
                rules={{
                    required: isDurationUnitRequired,
                    validate,
                }}
                render={({ field: durationUnitField, fieldState: durationUnitFieldState }) => (
                    <Controller<PaymentLinkCreationFormValues>
                        name="linkValidity.quantity"
                        control={control}
                        rules={{ required: isDurationQuantityRequired, validate }}
                        render={({ field: durationQuantityField, fieldState: durationQuantityFieldState }) => {
                            const onSelectInput = (e: SelectChangeEvent) => {
                                const newValue = (e.target as HTMLSelectElement)?.value;
                                if (newValue !== FLEXIBLE_ID) {
                                    const [value, durationUnit] = newValue?.split(' ') || [];
                                    durationQuantityField.onInput(value);
                                    durationUnitField.onInput(durationUnit);
                                    durationQuantityField.triggerValidation();
                                    durationUnitField.triggerValidation();
                                } else {
                                    durationUnitField.onInput('');
                                    durationQuantityField.onInput('');
                                    setCustomDurationQuantity(undefined);
                                    setCustomDurationUnit('');
                                }
                                setValidityValue(newValue);
                            };

                            const isInvalid =
                                (durationQuantityFieldState.error || durationUnitFieldState.error) &&
                                durationQuantityFieldState.isTouched &&
                                durationUnitFieldState.isTouched;
                            const isValid = !durationQuantityFieldState.error || !durationUnitFieldState.error;
                            const errorMessage = durationQuantityFieldState.error?.message || durationUnitFieldState.error?.message;

                            return (
                                <div>
                                    <div className="adyen-pe-payment-link-creation-form__validity-container">
                                        <FormField
                                            label={i18n.get('payByLink.creation.fields.validity.label')}
                                            supportText={i18n.get('payByLink.creation.fields.validity.supportText')}
                                            optional={!isDurationUnitRequired && !isDurationQuantityRequired}
                                            testId="form-field-linkValidity.durationUnit"
                                        >
                                            <Select
                                                selected={validityValue}
                                                onChange={onSelectInput}
                                                items={validitySelectItems}
                                                isValid={isValid}
                                                isInvalid={!validityValue}
                                                readonly={isReadOnly}
                                            />
                                        </FormField>
                                        {validityValue === FLEXIBLE_ID && (
                                            <FormField
                                                label={i18n.get('payByLink.creation.fields.validity.customDuration.label')}
                                                optional={false}
                                                testId="form-field-linkValidity.quantity"
                                            >
                                                <InputBase
                                                    {...durationQuantityField}
                                                    dropdown={{
                                                        ...durationUnitField,
                                                        items: dropdownItems,
                                                        value: customDurationUnit || '',
                                                        readonly: isReadOnly,
                                                    }}
                                                    onDropdownInput={handleCustomDurationUnitChange}
                                                    dropdownPosition="end"
                                                    value={customDurationQuantity}
                                                    type="number"
                                                    onInput={handleCustomDurationQuantityChange}
                                                    isValid={isValid}
                                                    isInvalid={isInvalid}
                                                    readonly={isReadOnly}
                                                />
                                            </FormField>
                                        )}
                                    </div>
                                    {isInvalid && errorMessage && (
                                        <FieldError errorMessage={errorMessage} testId="field-error-linkValidity.quantity" withTopMargin />
                                    )}
                                </div>
                            );
                        }}
                    />
                )}
            />
        </VisibleField>
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/PaymentDetailsForm/fields/ValidityField.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { BentoDropdown, BentoInputField } from '@adyen/bento-vue3';
import FieldWrapper from '../../../fields/FieldWrapper.vue';
import { useWizard } from '../../../../composables/wizardContext';
import { FLEXIBLE_VALIDITY_ID, LINK_VALIDITY_DURATION_UNITS } from '../../../../../../../domain/src';
import type { IPaymentLinkValidity } from '@integration-components/types';
import type { TranslationKey } from '@integration-components/core';
import './ValidityField.scss';

const props = defineProps<{
    options?: IPaymentLinkValidity[];
}>();

const wizard = useWizard();
const { i18n } = wizard;
const config = computed(() => wizard.getFieldConfig('linkValidity.durationUnit'));
const required = computed(() => config.value.required || wizard.getFieldConfig('linkValidity.quantity').required);
const error = computed(() => wizard.getError('linkValidity.quantity'));

const presetItems = computed(() =>
    (props.options ?? []).map(({ quantity, durationUnit, type }) => {
        if (type === FLEXIBLE_VALIDITY_ID) {
            return { label: i18n.get('payByLink.creation.fields.validity.linkValidityUnit.custom'), value: FLEXIBLE_VALIDITY_ID };
        }
        const key = `payByLink.creation.fields.validity.linkValidityUnit.${durationUnit}` as TranslationKey;
        return { label: i18n.get(key, { values: { quantity }, count: quantity }), value: `${quantity} ${durationUnit}` };
    })
);

const unitItems = computed(() =>
    LINK_VALIDITY_DURATION_UNITS.map(unit => ({
        label: i18n.get(`payByLink.creation.fields.validity.linkValidityUnit.${unit}__plural` as TranslationKey),
        value: unit,
    }))
);

const selection = ref('');
const quantity = computed(() => (wizard.values.value['linkValidity.quantity'] as string | number | undefined) ?? '');
const unit = computed(() => (wizard.values.value['linkValidity.durationUnit'] as string | undefined) ?? '');

function resolveSelection() {
    const q = wizard.getValue('linkValidity.quantity');
    const u = wizard.getValue('linkValidity.durationUnit');
    if (!q || !u) return presetItems.value[0]?.value ?? '';
    const match = presetItems.value.find(item => item.value === `${q} ${u}`);
    return match ? match.value : FLEXIBLE_VALIDITY_ID;
}

watch(
    presetItems,
    items => {
        if (!items.length) return;
        const q = wizard.getValue('linkValidity.quantity');
        const u = wizard.getValue('linkValidity.durationUnit');
        if (!q || !u) {
            const [firstQty, firstUnit] = `${items[0]?.value}`.split(' ');
            if (firstQty && firstUnit && items[0]?.value !== FLEXIBLE_VALIDITY_ID) {
                wizard.setValue('linkValidity.quantity', firstQty);
                wizard.setValue('linkValidity.durationUnit', firstUnit);
            }
        }
        selection.value = resolveSelection();
    },
    { immediate: true }
);

function onPresetUpdate(value: string | number | { value?: string | number } | Array<unknown> | undefined) {
    if (Array.isArray(value)) return;
    const next = typeof value === 'object' && value !== null ? value.value : value;
    if (next === undefined) return;
    const stringValue = String(next);
    selection.value = stringValue;
    if (stringValue !== FLEXIBLE_VALIDITY_ID) {
        const [qty, durationUnit] = stringValue.split(' ');
        wizard.setValue('linkValidity.quantity', qty);
        wizard.setValue('linkValidity.durationUnit', durationUnit);
    } else {
        wizard.setValue('linkValidity.quantity', '');
        wizard.setValue('linkValidity.durationUnit', '');
    }
}

function onQuantityInput(value: string | number) {
    wizard.setValue('linkValidity.quantity', value);
}

function onUnitUpdate(value: string | number | { value?: string | number } | Array<unknown> | undefined) {
    if (Array.isArray(value)) return;
    const next = typeof value === 'object' && value !== null ? value.value : value;
    if (next === undefined) return;
    wizard.setValue('linkValidity.durationUnit', String(next));
}
</script>

<template>
    <div v-if="config.visible" class="adyen-pe-payment-link-creation-form__validity-container">
        <FieldWrapper name="linkValidity.durationUnit">
            <BentoDropdown
                :items="presetItems"
                :label="i18n.get('payByLink.creation.fields.validity.label')"
                :description="i18n.get('payByLink.creation.fields.validity.supportText')"
                :placeholder="i18n.get('common.inputs.select.placeholder')"
                :model-value="selection"
                :optional="!required"
                :readonly="config.readOnly"
                @update:model-value="onPresetUpdate"
            />
        </FieldWrapper>
        <FieldWrapper v-if="selection === FLEXIBLE_VALIDITY_ID" name="linkValidity.quantity" :error="error">
            <div class="adyen-pe-payment-link-creation-form__validity-custom">
                <BentoInputField
                    :label="i18n.get('payByLink.creation.fields.validity.customDuration.label')"
                    type="number"
                    :model-value="quantity"
                    :min="1"
                    :readonly="config.readOnly"
                    :error="!!error"
                    @input="onQuantityInput"
                />
                <BentoDropdown
                    :items="unitItems"
                    :placeholder="i18n.get('common.inputs.select.placeholder')"
                    :model-value="unit"
                    :readonly="config.readOnly"
                    :error="!!error"
                    @update:model-value="onUnitUpdate"
                />
            </div>
        </FieldWrapper>
    </div>
</template>
