// packages/domains/payByLink/preact/src/PaymentLinkCreation/components/Form/CustomerDetailsForm/Fields/LanguageField.tsx
import { PaymentLinkCreationFormValues } from '../../../../types';
import { useCoreContext } from '@integration-components/core/preact';
import { useCallback, useMemo } from 'preact/hooks';
import { useFetch } from '@integration-components/hooks-preact';
import { FormSelect } from '@integration-components/ui-components-preact/FormWrappers/FormSelect';
import { useWizardFormContext } from '@integration-components/hooks-preact/form/wizard/WizardFormContext';

export const LanguageField = () => {
    const { i18n, getCdnDataset } = useCoreContext();
    const { fieldsConfig } = useWizardFormContext<PaymentLinkCreationFormValues>();

    const configCountryList = useMemo(() => {
        return fieldsConfig?.['shopperLocale']?.options as string[] | undefined;
    }, [fieldsConfig]);

    const languagesQuery = useFetch({
        fetchOptions: { enabled: true },
        queryFn: useCallback(async () => {
            if (getCdnDataset) {
                return (
                    (await getCdnDataset<Array<{ text: string; value: string | null }>>({
                        name: 'languages',
                        extension: 'json',
                        fallback: [] as Array<{ text: string; value: string | null }>,
                    })) ?? []
                );
            }
            return [] as Array<{ text: string; value: string | null }>;
        }, [getCdnDataset]),
    });

    const localeListItems = useMemo(() => {
        const langs = languagesQuery.data ?? [];

        return langs
            .filter(({ value }) => {
                return configCountryList?.length ? configCountryList?.includes(value as string) : true;
            })
            .map(({ text, value }) => {
                return {
                    // TODO - Handle 'auto detect' option when submitting information to the BE
                    id: value === null ? 'auto' : value,
                    name: text,
                };
            })
            .sort(({ name: a }, { name: b }) => a.localeCompare(b));
    }, [languagesQuery.data, configCountryList]);

    const isRequired = useMemo(() => fieldsConfig['shopperLocale']?.required, [fieldsConfig]);

    const shouldHideField = useMemo(() => {
        const hasItems = localeListItems.length > 0;

        return !languagesQuery.isFetching && !hasItems && !isRequired;
    }, [languagesQuery.isFetching, localeListItems.length, isRequired]);

    if (shouldHideField) return null;

    return (
        <FormSelect<PaymentLinkCreationFormValues>
            filterable
            fieldName="shopperLocale"
            label={i18n.get('payByLink.creation.fields.language.label')}
            items={localeListItems}
            readonly={languagesQuery.isFetching}
        />
    );
};

// packages/domains/payByLink/vue/src/PaymentLinkCreation/components/Form/CustomerDetailsForm/fields/LanguageField.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import SelectField from '../../../fields/SelectField.vue';
import { useCoreContext } from '@integration-components/core/vue';
import { useWizard } from '../../../../composables/wizardContext';

const wizard = useWizard();
const { i18n, getCdnDataset } = useCoreContext();

const config = computed(() => wizard.getFieldConfig('shopperLocale'));
const configOptions = computed(() => (config.value.options as string[] | undefined) ?? []);

const languages = ref<Array<{ text: string; value: string | null }>>([]);
const isFetching = ref(true);

onMounted(async () => {
    try {
        if (getCdnDataset) {
            languages.value =
                (await getCdnDataset<Array<{ text: string; value: string | null }>>({ name: 'languages', extension: 'json', fallback: [] })) ?? [];
        }
    } finally {
        isFetching.value = false;
    }
});

const localeItems = computed(() =>
    languages.value
        .map(({ text, value }) => ({ id: value === null ? 'auto' : value, name: text }))
        .filter(({ id }) => (configOptions.value.length ? configOptions.value.includes(id as string) : true))
        .sort((a, b) => a.name.localeCompare(b.name))
);

const shouldHide = computed(() => !isFetching.value && localeItems.value.length === 0 && !config.value.required);
</script>

<template>
    <SelectField
        v-if="config.visible && !shouldHide"
        name="shopperLocale"
        :label="i18n.get('payByLink.creation.fields.language.label')"
        :items="localeItems"
        filterable
    />
</template>
