// packages/domains/payByLink/vue/src/PaymentLinkDetails/components/PaymentLinkTabs/PaymentLinkTabs.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { BentoTab, BentoTabs } from '@adyen/bento-vue3';
import { useCoreContext } from '@integration-components/core/vue';
import useTimezoneAwareDateFormatting from '@integration-components/composables-vue/useTimezoneAwareDateFormatting';
import { buildPaymentLinkListItems } from '@integration-components/payByLink/domain';
import type { IPaymentLinkDetails } from '@integration-components/types';
import PaymentLinkActivity from '../PaymentLinkActivity/PaymentLinkActivity.vue';
import PaymentLinkTabsList from './PaymentLinkTabsList.vue';
import './PaymentLinkTabs.scss';

const CLASSNAMES = {
    root: 'adyen-pe-payment-link-tabs',
};

const props = defineProps<{
    paymentLink: IPaymentLinkDetails;
}>();

const { i18n } = useCoreContext();
const { dateFormat } = useTimezoneAwareDateFormatting();

const tabs = [
    { id: 'linkInformation', label: 'payByLink.details.tabs.linkInformation' },
    { id: 'shopperInformation', label: 'payByLink.details.tabs.shopperInformation' },
    { id: 'activity', label: 'payByLink.details.tabs.activity' },
] as const;

const activeTabIndex = ref(0);

function onTabChange(index: number) {
    activeTabIndex.value = index;
}

const listItems = computed(() => buildPaymentLinkListItems(props.paymentLink, { i18n, dateFormat }));
</script>

<template>
    <div :class="CLASSNAMES.root">
        <BentoTabs :active-tab-index="activeTabIndex" @update:active-tab-index="onTabChange">
            <BentoTab v-for="tab in tabs" :key="tab.id" :title="i18n.get(tab.label)">
                <PaymentLinkTabsList v-if="tab.id === 'linkInformation'" :items="listItems.linkInformation" />

                <template v-else-if="tab.id === 'shopperInformation'">
                    <PaymentLinkTabsList :items="listItems.shopperInformation" />

                    <div v-if="listItems.shippingAddress.length > 0">
                        <PaymentLinkTabsList :heading="'payByLink.details.fields.shippingAddress.title'" :items="listItems.shippingAddress" />
                    </div>

                    <div v-if="listItems.billingAddress.length > 0">
                        <PaymentLinkTabsList :heading="'payByLink.details.fields.billingAddress.title'" :items="listItems.billingAddress" />
                    </div>
                </template>

                <PaymentLinkActivity v-else-if="tab.id === 'activity'" :activities="paymentLink.paymentLinkActivities ?? []" />
            </BentoTab>
        </BentoTabs>
    </div>
</template>

// packages/domains/payByLink/preact/src/PaymentLinkDetails/components/PaymentLinkTabs/PaymentLinkTabs.tsx
import { useCoreContext } from '@integration-components/core/preact';
import { useCallback, useMemo } from 'preact/hooks';
import StructuredList from '@integration-components/ui-components-preact/StructuredList';
import { ListValue, StructuredListItem, StructuredListItemType } from '@integration-components/ui-components-preact/StructuredList/types';
import Tabs from '@integration-components/ui-components-preact/Tabs/Tabs';
import { useTimezoneAwareDateFormatting } from '@integration-components/hooks-preact';
import { IPaymentLinkDetails } from '@integration-components/types';
import { TypographyVariant } from '@integration-components/ui-components-preact/Typography/types';
import Typography from '@integration-components/ui-components-preact/Typography/Typography';
import { PaymentLinkActivity } from '../PaymentLinkActivity/PaymentLinkActivity';
import { TabProps } from '@integration-components/ui-components-preact/Tabs/types';
import './PaymentLinkTabs.scss';
import { TranslationKey } from '@integration-components/core';
import CopyText from '@integration-components/ui-components-preact/CopyText/CopyText';
import { BACKEND_REDACTED_DATA_MARKER, FRONTEND_REDACTED_DATA_MARKER, buildPaymentLinkListItems } from '@integration-components/payByLink/domain';
import Link from '@integration-components/ui-components-preact/Link/Link';

const CLASSNAMES = {
    root: 'adyen-pe-payment-link-tabs',
    list: 'adyen-pe-payment-link-tabs__list',
    listHeading: 'adyen-pe-payment-link-tabs__list-heading',
    listLabel: 'adyen-pe-payment-link-tabs__list-label',
    listValue: 'adyen-pe-payment-link-tabs__list-value',
};

type PaymentLinkTabsProps = {
    paymentLink: IPaymentLinkDetails;
};

export const PaymentLinkTabs = ({ paymentLink }: PaymentLinkTabsProps) => {
    const { i18n } = useCoreContext();
    const { dateFormat } = useTimezoneAwareDateFormatting();

    const listItems = useMemo(() => {
        const items = buildPaymentLinkListItems(paymentLink, { i18n, dateFormat });
        const toStructuredListItems = (categoryItems: (typeof items)['linkInformation']): StructuredListItem[] =>
            categoryItems.map(({ key, value, isCopyable, linkUrl }) => ({
                key,
                value,
                config: { isCopyable, linkUrl },
            }));

        return {
            linkInformation: toStructuredListItems(items.linkInformation),
            shopperInformation: toStructuredListItems(items.shopperInformation),
            shippingAddress: toStructuredListItems(items.shippingAddress),
            billingAddress: toStructuredListItems(items.billingAddress),
        };
    }, [paymentLink, dateFormat, i18n]);

    const renderListItemLabel = useCallback((label: string) => <div className={CLASSNAMES.listLabel}>{label}</div>, []);
    const renderListItemValue = useCallback((value: ListValue, key: TranslationKey, type: StructuredListItemType | undefined, config: any) => {
        let transformedValue;
        if (value && value.toString().includes(BACKEND_REDACTED_DATA_MARKER)) {
            transformedValue = FRONTEND_REDACTED_DATA_MARKER;
        } else if (config?.isCopyable && value && value !== '') {
            const visibleText = config?.linkUrl ? (
                <Link href={config.linkUrl} target="_blank">
                    {value.toString()}
                </Link>
            ) : undefined;
            transformedValue = <CopyText textToCopy={value.toString()} visibleText={visibleText} type={'Default'} />;
        } else {
            transformedValue = value;
        }

        return <div className={CLASSNAMES.listValue}>{transformedValue}</div>;
    }, []);

    const tabs = useMemo<TabProps<string>[]>(
        () =>
            [
                {
                    id: 'linkInformation',
                    label: 'payByLink.details.tabs.linkInformation',
                    content: (
                        <StructuredList
                            classNames={CLASSNAMES.list}
                            items={listItems.linkInformation}
                            align="start"
                            layout="4-8"
                            renderLabel={renderListItemLabel}
                            renderValue={renderListItemValue}
                        />
                    ),
                },
                {
                    id: 'shopperInformation',
                    label: 'payByLink.details.tabs.shopperInformation',
                    content: (
                        <>
                            <StructuredList
                                classNames={CLASSNAMES.list}
                                items={listItems.shopperInformation}
                                align="start"
                                layout="4-8"
                                renderLabel={renderListItemLabel}
                                renderValue={renderListItemValue}
                            />

                            {listItems.shippingAddress.length > 0 && (
                                <>
                                    <Typography variant={TypographyVariant.CAPTION} stronger className={CLASSNAMES.listHeading}>
                                        {i18n.get('payByLink.details.fields.shippingAddress.title')}
                                    </Typography>
                                    <StructuredList
                                        classNames={CLASSNAMES.list}
                                        items={listItems.shippingAddress}
                                        align="start"
                                        layout="4-8"
                                        renderLabel={renderListItemLabel}
                                        renderValue={renderListItemValue}
                                    />
                                </>
                            )}

                            {listItems.billingAddress.length > 0 && (
                                <>
                                    <Typography variant={TypographyVariant.CAPTION} stronger className={CLASSNAMES.listHeading}>
                                        {i18n.get('payByLink.details.fields.billingAddress.title')}
                                    </Typography>
                                    <StructuredList
                                        classNames={CLASSNAMES.list}
                                        items={listItems.billingAddress}
                                        align="start"
                                        layout="4-8"
                                        renderLabel={renderListItemLabel}
                                        renderValue={renderListItemValue}
                                    />
                                </>
                            )}
                        </>
                    ),
                },
                {
                    id: 'activity',
                    label: 'payByLink.details.tabs.activity',
                    content: <PaymentLinkActivity activities={paymentLink.paymentLinkActivities ?? []} />,
                },
            ] as TabProps<string>[],
        [listItems, renderListItemLabel, renderListItemValue, i18n, paymentLink.paymentLinkActivities]
    );

    return (
        <div className={CLASSNAMES.root}>
            <Tabs tabs={tabs} />
        </div>
    );
};
